jwt:
  header: Authorization   #jwt的请求头
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl   #jwt的加密字符串
  expiration: 1800000  #jwt token有效时间（毫秒）（半个小时）
  refreshToken: 600000      #jwt 距离刷新时间(间隔10分钟)
server:
  port: 9093
